### ISSUE TITLE
`save` argument in `consensus_cluster`

### ISSUE THREAD

**Issue by ShanzhaoWang** [AlineTalhouk/diceR#125]
Hi Derek,

From the previous version of diceR, we used to have a `save` argument in the function `consensus_cluster`. But it disappears for the later version. 
Can you please add it back?

Thank you

**Comment by dchiu911** [comment]
The `save` argument was removed because it was redundant with the `file.name` argument. To save the output from `consensus_cluster`, specify a file name to `file.name`. Leaving `file.name` unspecified will not save the output. Please see how the saving is done [here](https://github.com/AlineTalhouk/diceR/blob/master/R/consensus_cluster.R#L160) and the documentation of `file.name` at `?consensus_cluster` for more details.
