### ISSUE TITLE
"Error in dist calculation" [diceR::dice()]

### ISSUE THREAD

**Issue by Asduveneck** [AlineTalhouk/diceR#127]
Hey there,

  Thank you so much for creating an amazing package. It has a lot of potential. I'm currently testing this package to score robust autotetraploid markers. I came across an error when I was testing the dice command on a subset of markers.

**UPDATE** The error seems to involve the dist() function when using cmeans. I removed the traceback because I don't know how useful it is. I am fairly new to this, so please let me know if there is anything I can do to provide assistance.  

##Session Info

R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

## Packages, Functions, code
```{r initial_error}
#package----
library(tidyr); library(dplyr); library(ggplot2); library(readr)
library(pander); library(diceR); library(data.table)
library(cowplot)
#data # needs to be more reproducible----
X_num_ln <- c(1, 1.1, 1.5, 1.6, 2, 2.1, 2.5, 2.6)
Y_num_ln <- c(5, 5.1, 4.6, 4.5, 1.6, 1.5, 1.1, 1)
marker <- c("A1", "A1", "A2", "A2", "B1", "B1", "B2", "B2")
data_scaled_polar <- cbind.data.frame(marker, X_num_ln, Y_num_ln) %>% group_by(marker) %>% nest()
#functions----
ensemble_cluster_xy2 <- function(mrk, alg, spec_dist) { #mrk: the markers you're testing this on. alg: algorithms, spec_dist: distance 
  data_scaled_CC <- lapply(mrk, function(i) {
  data_tmp <- data_scaled_polar$data[[i]] %>% select(X_num_ln, Y_num_ln) #this needs to be worked on later
  data_tmp_CC <- dice(data = data_tmp, reps = 10, nk = 2:10,
            algorithms = alg, distance = spec_dist, trim = TRUE, reweigh = TRUE, plot = FALSE)
  data_tmp_clustered <- bind_cols(data_scaled_polar$data[[i]], as.data.frame(data_tmp_CC$clusters))
  data_tmp_clustered$marker <- data_scaled_polar$marker[[i]] 
  return(data_tmp_clustered) #once you fine-tune this, select the proper clustering algorithm
}) %>% rbindlist() 
}
test_7a <- ensemble_cluster_xy2(mrk = 365:375, alg = c("ap", "cmeans", "gmm", "hc"), spec_dist = "euclidean") #I know in my example I didn't provide mrk this far down.
```
##Output
Clustering Algorithm 3 of 4: CMEANS (k = 8) [================================================================================================-----------------------------------------------]  67% eta:  3m
 Hide Traceback
Error in if (diffdist < minimum) minimum <- diffdist : missing value where TRUE/FALSE needed

##Additional Comments
  I was surprised because the same command worked for a different subset of markers (with identical formatting). 

##Updated version of the above function/code
```{r temp_fix}
ensemble_cluster_xy3 <- function(mrk, alg, nk) {
  data_scaled_CC <- lapply(mrk, function(i) {
  data_tmp <- data_scaled_polar$data[[i]] %>% select(X_num_ln, Y_num_ln) #this needs to be worked on later
  data_tmp_CC <- dice(data = data_tmp, reps = 10, 
     nk = nk, algorithms = alg,
     cons.funs = "kmodes", trim = TRUE, reweigh = TRUE, plot = FALSE)
  data_tmp_clustered <- bind_cols(data_scaled_polar$data[[i]], as.data.frame(data_tmp_CC$clusters))
  data_tmp_clustered$marker <- data_scaled_polar$marker[[i]] 
  return(list(data_tmp_clustered, data_tmp_CC)) 
})  
}
test_7a <- ensemble_cluster_xy3(mrk = 365:375, alg = c("ap", "gmm", "hc", "som"), nk = 3:7) 
```

**Comment by dchiu911** [comment]
Hi @Asduveneck 

First please provide a working reproducible example. When trying to run your commands I run into the errors
```
Error in data_scaled_polar$data[[i]] : subscript out of bounds
```
This is because the `data` list-column in object `data_scaled_polar` only has 2 by 2 tibbles and you are subsetting `mrk = 365:375`. Try creating a larger object. Another by-product of trying to cluster data of such small dimension is that algorithms will fail because only a subset of samples are selected in each iteration of `conseusus_cluster`. See argument `p.item` in `?consensus_cluster`. Its default value is 0.8, so trying to cluster 0.8 * 2  = 1.6 < 2 samples is impossible.

For example for `hc`
```
Error in stats::hclust(d, method = method) : 
  must have n >= 2 objects to cluster
```
And `ap`
```
Error in .local(s, x, ...) : cannot cluster less than 2 samples
```

**Comment by Asduveneck** [comment]
Sorry about the lack of a reproducible example. I just got permission to release some data. I uploaded a zip file containing sample data and code. 

  dice worked on markers g_1 and g_2, but not for b_1. I got rid of cmeans in a later test and got clustering results. 

[diceR.polyploid.zip](https://github.com/AlineTalhouk/diceR/files/1925185/diceR.polyploid.zip)

**Comment by dchiu911** [comment]
Hi @Asduveneck,

I believe certain randomly chosen initial cluster centers in `e1071::cmeans` are unable to produce a valid clustering (the entire output has `NaN` everywhere). Not sure why that is, something to do with the source implementation `e1071:::R_cmeans`. I've modified the fuzzy c-means algorithm to choose m using Equation 5 [here](https://academic.oup.com/bioinformatics/article/26/22/2841/227572). Thus you should no longer see the error
```
Error in if (diffdist < minimum) minimum <- diffdist : missing value where TRUE/FALSE needed
```
because I am not using `e1071::fclustIndex` anymore.

**Comment by Asduveneck** [comment]
Thank you so much. You really know your stuff!
