### ISSUE TITLE
Is PAC the best way to choose optimal k?

### ISSUE THREAD

**Issue by carcarre11** [AlineTalhouk/diceR#164]
Hi,
First of all congratulations on this wonderful package.  What happens to me, and makes sense, is that using the pac to choose the optimal k always gives me the largest k that I have tried as the optimal one. I am not an expert at all, but what I have done to solve this, is to apply a CDF over the consensus similarity matrix for all algorithms to each k, and then calculate the delta between each k and the next k obtaining the maximum difference, trying to keep the last k in which CDF difference starts to be small. This is because (at least in biology) sometimes as many groups you have better the clustering stability is, however, what you are looking for is to make groups that are affordable in a clinical or biological way. I'm sure that should be better ways to do that so I suggest may implement another way to select the best k and I hope that maybe you could say what could be the best option to do this.

**Comment by dchiu911** [comment]
Hi @carcarre11 that sounds like the Delta K approach in the paper referenced in `PAC()`, https://doi.org/10.1038%2Fsrep06207.

It appears that your data exhibit a pattern where PAC is a decreasing function of k, i.e. increasing the upper bound of potential cluster sizes changes the optimal k since the largest k always has the smallest PAC. I only implemented PAC as a method for choosing k as the paper showed that it outperformed the other methods.

**Comment by carcarre11** [comment]
That it is! I hadn't taken a look at that paper thanks for the reference. Many algorithms, many ways to apply the consensus, and many ways to obtain the optimum k, so great work to put things easier.
