### ISSUE TITLE
consensus_matrix on large scale single cell data

### ISSUE THREAD

**Issue by juechenyang** [AlineTalhouk/diceR#166]
Hello,

Thank you for developing this amazing package! I am actually trying to use this package to compute the optimal K for my single cell RNA seq data. However, When I got my clustering result matrix (which has rows representing samples and columns representing clustering assignment results), it is usually big (~40000 rows x ~100 columns). So when I input this clustering result matrix into consensus_matrix function in diceR, it always throw me "R Error: Cannot Allocate Vector of Size 13.2 GB". I know this is due to memory limitation but I have already reached to the memory cap of my machine and could not increase more memory availability.

Would you mind providing me some hint about how to solve this issue from either programming or algorithm prospective?
Thank you!

**Comment by dchiu911** [comment]
Hi @juechenyang thank you for your interest in this package. Have you tried all the suggestions from this [SO post](https://stackoverflow.com/questions/5171593/r-memory-management-cannot-allocate-vector-of-size-n-mb)? If all else fails, you might want to try calculating the consensus matrix by separately calculating the connectivity matrices and indicator matrices so that your R session doesn't hang up from lack of memory.

See [Monti paper](https://link.springer.com/content/pdf/10.1023/A:1023949509487.pdf) for details and in `consensus_matrix()` the implementation of how the matrix is constructed.

You can try:

1. Open R session, calculate the list of 100 indicator matrices, sum together, save object, close R session.
2. Open new R session, calculate the list of 100 connectivity matrices, sum together, save object, close R session.
3. Divide object from step 2 by object from step 1 elementwise to get the consensus matrix.
